version: '1'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/archive/stickermoney.su:/etc/letsencrypt/archive/stickermoney.su
      - /etc/letsencrypt/archive/stickermoney.su:/etc/letsencrypt/archive/stickermoney.su
